**Изучение библиотеки math**

In [ ]:
import math
angle_in_radians = math.pi/8 #22.5 градуса
angle_in_radians

0.39269908169872414

**Перевод градусов в радианы**

In [ ]:
angle_in_degrees = angle_in_radians * 180 / math.pi #Переводим pi/8 в градусы
angle_in_degrees 

22.5

**Перевод радиан в градусы**

In [8]:
angle_to_radians = angle_in_degrees * math.pi / 180 #Переводим 22.5 градуса в радианы
angle_to_radians 

0.39269908169872414

**импорт NumPy и работа с массивами**

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5]) #Массив с помощью NumPy
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.zeros(5) #Массив из нулей
arr2

array([0., 0., 0., 0., 0.])

In [ ]:
arr3 = np.ones(5) #Массив из единиц
arr3

array([1., 1., 1., 1., 1.])

In [26]:
arr4 = np.arange(5) #Массив, заданный с помощью arange
arr4

array([0, 1, 2, 3, 4])

**Вывод формы**

In [17]:
arr_shape = np.array([52,36,67,12])
np.shape(arr_shape)

(4,)

**Вывод типа данных массива**

In [18]:
arr_shape.dtype

dtype('int64')

**Получение отдельного элемента по индексу**

In [ ]:
last_element = arr1[-1] #Вывод последнего элемента массива
last_element

np.int64(5)

**извлечение подмассива с помощью среза**

In [ ]:
slice = arr1[0:4:2] #Вывод среза с первого по последний элемент с шагом 2
slice

array([1, 3])

**Поэлементное сложение массивов**

In [23]:
sum1 = arr1+arr3
sum1

array([2., 3., 4., 5., 6.])

**Поэлементное умножение массивов**

In [27]:
sum2 = arr1*arr4
sum2

array([ 0,  2,  6, 12, 20])

**Вычисление среднего значения массивов**

In [28]:
mean_v = np.mean(arr1)
mean_v

np.float64(3.0)

**Вычисление медианного значения массива**

In [29]:
median_v = np.median(arr4)
median_v

np.float64(2.0)